### ISSUE TITLE
fzf erases scrollback buffer on Windows

### ISSUE THREAD

**Issue by wjrogers** [junegunn/fzf#1766]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] cmd
    - [x] powershell
    - [x] pwsh (PowerShell Core)

## Problem / Steps to reproduce

1. Open a new Command Prompt
1. Generate some terminal buffer content with e.g. `dir` or `tree`
1. Run `fzf`
1. Hit ESC to exit
1. Observe the terminal buffer has been erased and the scrollback cleared

Interestingly, in the new [Windows Terminal](https://github.com/microsoft/terminal), the problem is less severe: only the visible lines in the terminal are erased when running `fzf`. Anything in the scrollback buffer is still there afterward.

**Comment by LuRsT** [comment]
Hi @wjrogers, if you set the `--height` option, you can make `fzf` smaller, which should at least erase fewer lines. Also, if you use the option `--reverse`, it opens below the prompt, which may completely solve your issue.

**Comment by wjrogers** [comment]
@LuRsT I am using `--reverse`, and passing `--height` gives the message "--height option is currently not supported on Windows"

**Comment by KindDragon** [comment]
@wjrogers  PR #1341 should fix this

**Comment by wjrogers** [comment]
I just tested in 0.24.1, and this bug is not fixed. Will you please re-open? (@KindDragon's comment was referring to the `--height` option, which _is_ now supported on Windows.)

**Comment by junegunn** [comment]
So this problem only happens when you don't use `--height` option?

**Comment by wjrogers** [comment]
Correct. Using `--height` works around it because it scrolls the terminal far enough for the fzf "window" to fit below the prompt.

**Comment by junegunn** [comment]
Can you test if this binary helps in your case? I don't have a Windows environment to test it now.

- [fzf-0.24.1-devel-windows_amd64.zip](https://github.com/junegunn/fzf/files/5466170/fzf-0.24.1-devel-windows_amd64.zip)

It just makes fzf use the new renderer instead of tcell library when it's available.

```diff
diff --git a/src/terminal.go b/src/terminal.go
index 778665a..8697d21 100644
--- a/src/terminal.go
+++ b/src/terminal.go
@@ -408,11 +408,11 @@ func NewTerminal(opts *Options, eventBox *util.EventBox) *Terminal {
 	var renderer tui.Renderer
 	fullscreen := opts.Height.size == 0 || opts.Height.percent && opts.Height.size == 100
 	if fullscreen {
-		if tui.HasFullscreenRenderer() {
-			renderer = tui.NewFullscreenRenderer(opts.Theme, opts.Black, opts.Mouse)
-		} else {
+		if tui.IsLightRendererSupported() {
 			renderer = tui.NewLightRenderer(opts.Theme, opts.Black, opts.Mouse, opts.Tabstop, opts.ClearOnExit,
 				true, func(h int) int { return h })
+		} else if tui.HasFullscreenRenderer() {
+			renderer = tui.NewFullscreenRenderer(opts.Theme, opts.Black, opts.Mouse)
 		}
 	} else {
 		maxHeightFunc := func(termHeight int) int {
```

**Comment by wjrogers** [comment]
Yes, that binary completely fixes the bug! Tested both Command Prompt and Windows Terminal. Windows 20H2 (19042.610).

**Comment by junegunn** [comment]
Thanks for the confirmation. Patch pushed to master. Please report any issues you run into.

/cc @kelleyma49

**Comment by vovcacik** [comment]
The tcell library used in FullscreenRenderer is [clipping][] the console's buffer to the size of console's window during initialization (and few more occasions). There was an effort to preserve the buffer and restore it on exit gdamore/tcell#288.

You could also switch to LightRenderer with `fzf --height=99%`.

[clipping]: https://github.com/gdamore/tcell/blob/fcaa20f283682d6bbe19ceae067b37df3dc699d7/console_win.go#L991
