### ISSUE TITLE
Preview window wrap cuts lines with ANSI colors

### ISSUE THREAD

**Issue by ddnexus** [junegunn/fzf#2346]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

The `--preview-window=wrap` cuts part of the lines that contain a colored word which start or end falls on the right margin being wrapped.

You can try with this simple line:

```zsh
zsh -c "seq 10 | fzf --preview-window=wrap:right:40% --preview='print -P -- one two three four five six %F{red}seven%f eight nine ten'"
```
As you will see the `seven` is shown in red color. Now resize/reduce the width of the terminal window until the right margin arrives to the end of the `seven` word. At that point the "eight nine ten" will just disappear. 

Continue to reduce the size and you will see that it will work again, wrapping the line as expected when the `seven` is split in two, but if you continue to reduce the size until the margin will reach the start of the `seven` word you will see that "seven eight nine ten" will disappear again.

Notice: this is not a problem with the dynamic resizing, but with the fact that a text containing colored words will get partially truncated depending on where the colored words fall in the preview window.

**Comment by junegunn** [comment]
It should be fixed now, thanks for the report.

**Comment by ddnexus** [comment]
I built the 8ae94f0 but I still get the same problem (running the example line of my previous message).

**Comment by ddnexus** [comment]
There is a little difference though. Narrowing the window at a certain size it makes disappear the `seven` but shows the rest of the second line. Then narrowing more, all reappears and works.

**Comment by junegunn** [comment]
You're right. This is trickier than I expected 🤔

**Comment by junegunn** [comment]
I believe it's fixed now on the master branch. Please let me know if you still see the problem.

**Comment by ddnexus** [comment]
Fixed! Tank you so much for your great work ad support!
