### ISSUE TITLE
FZF locks up zsh under tmux with C-R on open subshell interpolation

### ISSUE THREAD

**Issue by ggilder** [junegunn/fzf#435]
In zsh under tmux, if I have a partial command typed like `foo $(bar` and I try to use `C-R` to search command history, fzf attempts to evaluate the subshell rather than passing the literal command string through. Because the subshell interpolation is unclosed, it then hangs. I have to kill the fzf-tmux process from another shell.

I can verify this because `C-R` on `foo $(echo bar)` gets sent through to fzf as `foo bar`.

**Comment by junegunn** [comment]
I believe I fixed the issue a while ago; see #404. Are you running the latest version?

**Comment by ggilder** [comment]
I just tried updating (to 0.10.9) and the problem still occurs unfortunately :cry:

**Comment by ggilder** [comment]
Oh, I see that commit is probably not released yet. Let me try on master

**Comment by ggilder** [comment]
Yup, works fine on master. By the way should some version of 0.11.x be released on Homebrew?

**Comment by junegunn** [comment]
Yeah, I don't use homebrew to install fzf so it was not my priority, and I was hoping someone sends a PR for the new tag to Homebrew; as in https://github.com/Homebrew/homebrew/pull/45720
