### ISSUE TITLE
FZF_COMPLETION_DIR_OPTS not respected when _fzf_compgen_dir is defined

### ISSUE THREAD

**Issue by Maple38** [junegunn/fzf#4592]
### Checklist

- [x] I have read through the manual page (`man fzf`)
- [x] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.66.1 (brew)

### OS

- [ ] Linux
- [x] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [x] zsh
- [ ] fish

### Problem / Steps to reproduce

Hi!

I was running into an issue where my `FZF_COMPLETION_DIR_OPTS` and `FZF_COMPLETION_PATH_OPTS` were not being respected. After much troubleshooting, it seems the issue only occurs when `_fzf_compgen_path` and `_fzf_compgen_dir` are defined.

Is there a way to fix this?

If it matters, here's the part of my .zshrc:
```
export FZF_DEFAULT_COMMAND='fd --hidden --follow'
export FZF_DEFAULT_OPTS='--style full'

export FZF_COMPLETION_OPTS='--style full'
export FZF_COMPLETION_DIR_OPTS='--preview="ls {}"'
export FZF_COMPLETION_PATH_OPTS='--preview="bat --color=always --style=numbers --line-range=:250 {}"'

_fzf_compgen_path() {
  fd -d 1 --type f --hidden --follow "$1"
}
_fzf_compgen_dir() {
  fd -d 1 --type d --hidden --follow "$1"
}
```

**Comment by LangLangBart** [comment]
> Is there a way to fix this?

can u add these function to your setup and check if its working as expected ?

```bash
_fzf_path_completion() {
  __fzf_generic_path_completion "$1" "$2" _fzf_compgen_path \
    "${FZF_COMPLETION_PATH_OPTS-} -m" "" " "
}

_fzf_dir_completion() {
  __fzf_generic_path_completion "$1" "$2" _fzf_compgen_dir \
    "${FZF_COMPLETION_DIR_OPTS-}" "/" ""
}
```

---

if it does then the patch would just be:

```diff
--- a/shell/completion.zsh
+++ b/shell/completion.zsh
@@ -205,10 +205,10 @@ __fzf_generic_path_completion() {
 _fzf_path_completion() {
   __fzf_generic_path_completion "$1" "$2" _fzf_compgen_path \
-    "-m" "" " "
+    "${FZF_COMPLETION_PATH_OPTS-} -m" "" " "
 }
 
 _fzf_dir_completion() {
   __fzf_generic_path_completion "$1" "$2" _fzf_compgen_dir \
-    "" "/" ""
+    "${FZF_COMPLETION_DIR_OPTS-}" "/" ""
 }
```

**Comment by Maple38** [comment]
Doesn't appear to fix it sadly.

**Comment by LangLangBart** [comment]
> Doesn't appear to fix it sadly.

did you add `_fzf_path_completion` and `_fzf_dir_completion` after running `source <(fzf --zsh)`

what is the output for `typeset -f _fzf_path_completion` ?

**Comment by Maple38** [comment]
> > Doesn't appear to fix it sadly.
> 
> did you add `_fzf_path_completion` and `_fzf_dir_completion` after running `source <(fzf --zsh)`
> 
> what is the output for `typeset -f _fzf_path_completion` ?

Oh wait, it does work now. Your solution did work. Not entirely sure what I did wrong when copy-pasting the first time, but it's fixed now! Thank you very much.

**Comment by jathek** [comment]
This fix works for me as well, but the path completion still doesn't obey the height argument. The dir completion *does* obey the height argument, so I'm not sure what I'm missing. The path completion does change the label properly, so it's reading the variable.

fzf: `0.67.0 (2ab923f3)`
zsh: `zsh 5.9 (x86_64-slackware-linux-gnu)`
uname -a: `Linux Tower 6.12.54-Unraid #1 SMP PREEMPT_DYNAMIC Tue Oct 21 15:58:46 PDT 2025 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux`
cat /etc/os-release:
```
NAME="Unraid OS"
ID="unraid-os"
ID_LIKE="slackware"
PRETTY_NAME="Unraid OS 7.2 x86_64"
CPE_NAME="cpe:/o:limetech:unraid-os:7.2.3"
VERSION="7.2.3 2025-12-18"
VERSION_ID="7.2.3"
VERSION_CODENAME="stable"
HOME_URL="https://unraid.net/"
SUPPORT_URL="https://support.unraid.net/"
BUG_REPORT_URL="https://forums.unraid.net/"
DOCUMENTATION_URL="https://docs.unraid.net/"
VENDOR_NAME="Lime Technology, Inc."
```

<details>
<summary>fzf config</summary>

```sh
## fzf https://github.com/junegunn/fzf/#table-of-contents
# fzf update
source /boot/custom/scripts/fzfupdate.source
# Set up fzf key bindings and fuzzy completion
[ "${ACTIVE_SHELL}" = "bash" ] && source <(fzf --bash)
[ "${ACTIVE_SHELL}" = "zsh" ] && source <(fzf --zsh)
# Default command to use when input is tty
export FZF_DEFAULT_COMMAND="command fd --color=always --exclude .git --unrestricted"
# ctrl-t command
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
# defaults
export FZF_DEFAULT_OPTS="
  --ansi \
  --exact \
  --multi \
  --reverse \
  --wrap \
  --cycle \
  --style full \
  --border \
  --padding 1,2 \
  --border-label ' fzf ' --input-label ' input ' --header-label ' file type ' \
  --color 'border:#aaaaaa,label:#cccccc' \
  --color 'preview-border:#9999cc,preview-label:#ccccff' \
  --color 'list-border:#669966,list-label:#99cc99' \
  --color 'input-border:#996666,input-label:#ffcccc' \
  --color 'header-border:#6699cc,header-label:#99ccff' \
  --preview 'fzf-preview.sh {}' \
  --bind 'result:transform-list-label:
        if [[ -z \$FZF_QUERY ]]; then
          echo \" \$FZF_MATCH_COUNT items \"
        else
          echo \" \$FZF_MATCH_COUNT matches for [\$FZF_QUERY] \"
        fi
        ' \
  --bind 'focus:transform-preview-label:[[ -n {} ]] && printf \" previewing [%s] \" {}' \
  --bind 'focus:+transform-header:file -p --brief {} || echo \"no file selected\"' \
  --bind 'ctrl-r:change-list-label( reloading the list )+reload(sleep 1.5; ${FZF_DEFAULT_COMMAND})' \
  --bind 'ctrl-/:toggle-preview' \
  --bind 'ctrl-s:change-preview-window(99%|30%|50%)+refresh-preview' \
  --bind resize:refresh-preview \
  "
export FZF_CTRL_T_OPTS="${FZF_DEFAULT_OPTS} --preview-window 'hidden,follow,~3'"
# completion options - https://github.com/junegunn/fzf/#customizing-fzf-options-for-completion
export FZF_COMPLETION_TRIGGER='~~'
export FZF_COMPLETION_OPTS="--height '~40%' --preview-window 'right:50%'"
export FZF_COMPLETION_DIR_OPTS="--border-label ' fzf dir completion ' --preview 'command eza -1a --classify=always --color=always --group-directories-first --icons=always --no-quotes --show-symlinks {}'"
export FZF_COMPLETION_PATH_OPTS="--border-label ' fzf path completion '"
# Use fd for listing dir/path candidates - https://github.com/junegunn/fzf/#customizing-completion-source-for-paths-and-directories
# https://stackoverflow.com/a/29401114 - remove color codes before sorting and then readd them
_fzf_compgen_dir() {
  command fd --color=always --follow --exclude ".git" --unrestricted . "$1" --type dir | sed 'h;s/\x1b[[0-9;]*m//g;G;s/\n/\t/' | LC_COLLATE=en_US.UTF-8 LC_NUMERIC=en_US.UTF-8 sort -bdf | cut -f2-
}
_fzf_compgen_path() {
  command fd --color=always --follow --exclude ".git" --unrestricted . "$1" | sed 'h;s/\x1b[[0-9;]*m//g;G;s/\n/\t/' | LC_COLLATE=en_US.UTF-8 LC_NUMERIC=en_US.UTF-8 sort -bdf | cut -f2-
}
# fix for FZF_COMPLETION_*_OPTS not being respected - https://github.com/junegunn/fzf/issues/4592#issuecomment-3542129722
_fzf_path_completion() {
  __fzf_generic_path_completion "$1" "$2" _fzf_compgen_path \
    "${FZF_COMPLETION_PATH_OPTS-} -m" "" " "
}
_fzf_dir_completion() {
  __fzf_generic_path_completion "$1" "$2" _fzf_compgen_dir \
    "${FZF_COMPLETION_DIR_OPTS-}" "/" ""
}
```
</details>

**Comment by junegunn** [comment]
Patch pushed to master. Thanks @LangLangBart!
