### ISSUE TITLE
Unsupported key: options

### ISSUE THREAD

**Issue by jrock2004** [junegunn/fzf#765]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [X ] Neovim
    - [ ] Etc.
- OS
    - [ X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X ] zsh
    - [ ] fish

Just upgraded to newest version of neovim. Now when I reload and open fzf, I am getting error about unsupported key: options

Thoughts?

![image](https://cloud.githubusercontent.com/assets/655716/21119634/7b2a618c-c091-11e6-8617-5e80b3b27cd7.png)

**Comment by mhinz** [comment]
This should fix it:

```diff
diff --git i/plugin/fzf.vim w/plugin/fzf.vim
index 065701c..cb80b61 100644
--- i/plugin/fzf.vim
+++ w/plugin/fzf.vim
@@ -465 +465 @@ function! s:execute_term(dict, command, temps) abort
-  function! fzf.switch_back(inplace)
+  function! fzf.switch_back(inplace) dict
@@ -474 +474 @@ function! s:execute_term(dict, command, temps) abort
-  function! fzf.on_exit(id, code)
+  function! fzf.on_exit(id, code) dict
```

**Comment by junegunn** [comment]
Thanks @mhinz, but I'm still seeing errors with the patch :/

**Comment by justinmk** [comment]
`on_exit()` needs 3 arguments.

**Comment by gavsim** [comment]
I'm seeing the same errors with latest HEAD neovim and fzf

**Comment by supermarin** [comment]
@justinmk is right, adding a param to `on_exit` fixes things

``` diff
-  function! fzf.on_exit(id, code)
+  function! fzf.on_exit(id, code, wat)
```

**Comment by bradurani** [comment]
Still getting this with:

NVIM v0.2.0
0.16.8 (brew)
MacOS El Capitan 10.11.4

**Comment by Congee** [comment]
see this issue again with 0.21.1 (334a4fa)
