### ISSUE TITLE
"Too many arguments for function: 4" when trying to open any file in neovim

### ISSUE THREAD

**Issue by RatanRSur** [junegunn/fzf#769]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

After invoking `:FZF` in neovim on ubuntu server, pressing enter on any file gives:

`E118: Too many arguments for function: 4`

This does not happen on my Arch Linux machine and as far as I can tell, I've copied the necessary configuration files over. I just set up this Ubuntu 16.04 VM yesterday so all packages are at the most recent on those repos.

**Comment by deathmaz** [comment]
Are you using the latest version of fzf?
It seems that this problem is already solved https://github.com/junegunn/fzf/issues/765#issuecomment-266629073

**Comment by bradurani** [comment]
Still getting this with:

NVIM v0.2.0
0.16.8 (brew)
MacOS El Capitan 10.11.4
